// Generated by CoffeeScript 1.7.1
(function() {
  var should;

  should = require('should');

  describe('test', function() {
    it('should exists', function() {
      5..should.be.exactly(5).and.be.a.Number;
    });
  });

}).call(this);
